In [18]:
import numpy as np
import matplotlib.pyplot as plt
from skimage import io
import os


In [19]:
images=[]
labels=[]
files=os.listdir(r'processed_data')
for pimg in files:
    if pimg.endswith(('.png', '.jpg', '.jpeg')):
        image=io.imread(f'processed_data\\{pimg}').ravel()/255
        label=int(pimg.split('.')[0][-1])
        images.append(image)
        labels.append(label) 



In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.25, random_state=42)

In [21]:
xtrain = np.array([image for image in X_train])
ytrain = np.array(y_train)
xtrain[0]

array([0.75686275, 0.89411765, 0.97647059, ..., 0.99607843, 0.99607843,
       0.99607843])

In [22]:
xtest = np.array([image for image in X_test])
y_test = np.array(y_test)

In [ ]:

#MOdelling

In [23]:
from sklearn.neural_network import MLPClassifier
nn=MLPClassifier(verbose=True)
nn.fit(xtrain,ytrain.ravel())

Iteration 1, loss = 1.04306147
Iteration 2, loss = 17.55999581
Iteration 3, loss = 17.32895360
Iteration 4, loss = 16.41795299
Iteration 5, loss = 7.20748034
Iteration 6, loss = 12.97760060
Iteration 7, loss = 15.35068844
Iteration 8, loss = 12.63162172
Iteration 9, loss = 6.07933118
Iteration 10, loss = 10.92046892
Iteration 11, loss = 13.19731096
Iteration 12, loss = 10.80658441
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.


MLPClassifier(verbose=True)

In [24]:
ypred=nn.predict(xtest)
ypred,y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1]))

In [25]:
228*228//2//2//2//2


3249

In [26]:
from sklearn.neural_network import MLPClassifier
nn=MLPClassifier(hidden_layer_sizes=(784,228),activation='logistic',verbose=2)
nn.fit(xtrain,ytrain)

Iteration 1, loss = 1.10889690
Iteration 2, loss = 1.06006574
Iteration 3, loss = 1.09728156
Iteration 4, loss = 1.06514631
Iteration 5, loss = 1.03864346
Iteration 6, loss = 1.00643592
Iteration 7, loss = 0.97612364
Iteration 8, loss = 0.98081707
Iteration 9, loss = 1.00194059
Iteration 10, loss = 1.01233960
Iteration 11, loss = 1.00558042
Iteration 12, loss = 0.98948129
Iteration 13, loss = 0.97562911
Iteration 14, loss = 0.97284068
Iteration 15, loss = 0.97774696
Iteration 16, loss = 0.98507257
Iteration 17, loss = 0.98738488
Iteration 18, loss = 0.98713807
Iteration 19, loss = 0.98459414
Iteration 20, loss = 0.97979004
Iteration 21, loss = 0.97416274
Iteration 22, loss = 0.97054046
Iteration 23, loss = 0.96966634
Iteration 24, loss = 0.97073062
Iteration 25, loss = 0.97313348
Iteration 26, loss = 0.97449081
Iteration 27, loss = 0.97354382
Iteration 28, loss = 0.97076367
Iteration 29, loss = 0.96808471
Iteration 30, loss = 0.96622589
Iteration 31, loss = 0.96563958
Iteration 32, los

MLPClassifier(activation='logistic', hidden_layer_sizes=(784, 228), verbose=2)

In [27]:
ypred=nn.predict(xtest)
ypred,y_test

(array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1]))

In [31]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(nn,xtrain,ytrain)

TypeError: too many positional arguments

In [ ]:
from joblib import load
n=load('NN2')

In [ ]:
pred=n.predict_prob(np.array([Preprocessor(r'.data\Brown_spot\DSC_0100.jpg').transform()]))
pred[0,2]

In [ ]:
np.sum(pred)